name: Waka - Readme

on:
  schedule:
    - cron: '27 15 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.2.3
        with:
       
          WAKATIME_API_KEY: ${{ secrets.WAKAPI_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: last_30_days
          SHOW_TIME: true
